# Generated by Django 3.0.2 on 2020-02-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearrev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='episode',
            field=models.IntegerField(default=12),
        ),
    ]
